# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: csa
version: '0.1.0'
github: "volr/csa"
license: MIT
author: "Jens Egholm Pedersen"
maintainer: "Jens Egholm Pedersen"
synopsis: Connection-set algebra (CSA) library
description: Library for the production of connection matrices through CSA.
category: Algebra

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - hmatrix
  source-dirs: library

tests:
  csa-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - csa
    - hmatrix
    - hedgehog
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
